name: README.md

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - '.github/workflows/README.md.yml'

env:
  IMAGE: "buildroot ddns-go go-qrcode hello-world libqrencode minecraft-bedrock-server open-vm-tools ttnode"

jobs:
  README_md:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        if: github.event_name == 'schedule'
        run: |
          for i in ${{ env.IMAGE }}; do
            docker pull -a waterlemons2k/$i
          done

      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v3

      - name: Generate README.md
        if: github.event_name == 'push'
        run: |
          echo "# [Docker](https://hub.docker.com/u/waterlemons2k)" > README.md
          for i in ${{ env.IMAGE }}; do
            case $i in
              test)
                echo "- [$i](https://hub.docker.com/r/waterlemons2k/$i) [GitHub](../../../$i)" >> README.md;;
              *)
                echo "- [$i](https://hub.docker.com/r/waterlemons2k/$i) [GitHub](../../../Docker-$i)" >> README.md;;
            esac
          done

      - name: Git
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: sync Docker Image"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
