name: README.md

on:
  schedule:
    - cron: '0 0 1 */6 *'
  push:
    paths:
      - '.github/workflows/README.md.yml'

env:
  IMAGE: "buildroot ddns-go go-qrcode hello-world libqrencode minecraft-bedrock-server open-vm-tools ttnode"

jobs:
  README_md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate README.md
        run: |
          echo "# [Docker](https://hub.docker.com/u/waterlemons2k)" > README.md
          for i in $IMAGE; do
            docker pull -a waterlemons2k/$i
            case $i in
              test)
                echo "- [$i](../../../$i)" >> README.md;;
              *)
                echo "- [$i](../../../Docker-$i)" >> README.md;;
            esac
          done
          
      - name: Git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: sync Docker Image"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
