name: README.md

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - '.github/workflows/README.md.yml'

env:
  IMAGE: "buildroot ddns-go go-qrcode hello-world libqrencode minecraft-bedrock-server open-vm-tools ttnode upx"

jobs:
  keep-scheduled-workflow-activity:
    if: github.event_name == 'schedule'
    uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v1

  README_md:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        if: github.event_name == 'schedule'
        run: |
          for i in ${{ env.IMAGE }}; do
            docker pull waterlemons2k/$i
          done

      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v5

      - name: Generate README.md
        if: github.event_name == 'push'
        run: |
          {
            echo '# [Docker](https://hub.docker.com/u/waterlemons2k)'
            for i in ${{ env.IMAGE }}; do
              printf '%s' "- [$i](https://hub.docker.com/r/waterlemons2k/$i) [:octocat:](../../../"
              case $i in
                test)
                  echo "$i)";;
                upx)
                  echo "$i-docker)";;
                *)
                  echo "Docker-$i)";;
              esac
            done
          } >README.md

      - name: Git
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: sync Docker Image"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
